config/routes.rb
Rails.application.routes.draw do
	root 'food_recipes#index'
	get'search', to: "food_recipes#search"
	devise_for :users
	resources :food_recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_recipe.rb
class FoodRecipe < ApplicationRecord
	has_rich_text :ingredient
	has_rich_text :description
	has_rich_text :step

	mount_uploader :image, ImageUploader
	
	def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
  where("title LIKE ?", "%#{search}%")
end
end

app/models/receitum.rb
class Receitum < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/food_recipes_controller.rb
class FoodRecipesController < ApplicationController
  before_action :set_food_recipe, only: [:show, :edit, :update, :destroy]

  # GET /food_recipes
  # GET /food_recipes.json
  def index
    @food_recipes = FoodRecipe.all
  end

  def search
    @food_recipes = FoodRecipe.search(params[:q])
  end

  # GET /food_recipes/1
  # GET /food_recipes/1.json
  def show
  end

  # GET /food_recipes/new
  def new
    @food_recipe = FoodRecipe.new
  end

  # GET /food_recipes/1/edit
  def edit
  end

  # POST /food_recipes
  # POST /food_recipes.json
  def create
    @food_recipe = FoodRecipe.new(food_recipe_params)

    respond_to do |format|
      if @food_recipe.save
        format.html { redirect_to @food_recipe, notice: 'Food recipe was successfully created.' }
        format.json { render :show, status: :created, location: @food_recipe }
      else
        format.html { render :new }
        format.json { render json: @food_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_recipes/1
  # PATCH/PUT /food_recipes/1.json
  def update
    respond_to do |format|
      if @food_recipe.update(food_recipe_params)
        format.html { redirect_to @food_recipe, notice: 'Food recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_recipe }
      else
        format.html { render :edit }
        format.json { render json: @food_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_recipes/1
  # DELETE /food_recipes/1.json
  def destroy
    @food_recipe.destroy
    respond_to do |format|
      format.html { redirect_to food_recipes_url, notice: 'Food recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_recipe
      @food_recipe = FoodRecipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_recipe_params
      params.require(:food_recipe).permit(:remove_image, :image, :title, :description, :ingredient, :step)
    end
end

app/controllers/receita_controller.rb
class ReceitaController < ApplicationController
  before_action :set_receitum, only: [:show, :edit, :update, :destroy]

  # GET /receita
  # GET /receita.json
  def index
    @receita = Receitum.all
  end

  # GET /receita/1
  # GET /receita/1.json
  def show
  end

  # GET /receita/new
  def new
    @receitum = Receitum.new
  end

  # GET /receita/1/edit
  def edit
  end

  # POST /receita
  # POST /receita.json
  def create
    @receitum = Receitum.new(receitum_params)

    respond_to do |format|
      if @receitum.save
        format.html { redirect_to @receitum, notice: 'Receitum was successfully created.' }
        format.json { render :show, status: :created, location: @receitum }
      else
        format.html { render :new }
        format.json { render json: @receitum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receita/1
  # PATCH/PUT /receita/1.json
  def update
    respond_to do |format|
      if @receitum.update(receitum_params)
        format.html { redirect_to @receitum, notice: 'Receitum was successfully updated.' }
        format.json { render :show, status: :ok, location: @receitum }
      else
        format.html { render :edit }
        format.json { render json: @receitum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receita/1
  # DELETE /receita/1.json
  def destroy
    @receitum.destroy
    respond_to do |format|
      format.html { redirect_to receita_url, notice: 'Receitum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receitum
      @receitum = Receitum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receitum_params
      params.require(:receitum).permit(:title, :description)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :string, :description, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_recipes_helper.rb
module FoodRecipesHelper
end

app/helpers/receita_helper.rb
module ReceitaHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/food_recipes/_form.html.erb
<%= form_with(model: food_recipe, local: true) do |form| %>
  <% if food_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_recipe.errors.count, "error") %> prohibited this food_recipe from being saved:</h2>

      <ul>
        <% food_recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
      <%= form.file_field :image %>

      <% if @food_recipe.image? %>
        <%= image_tag @food_recipe.image.url, class: "food_recipe-show" %>
        <%= form.check_box :remove_image %>
        Remove Image
      <% end %>      
  </div>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.rich_text_area :description %>
  </div>
  
  <div class="field">
    <%= form.label :ingredients %>
    <%= form.rich_text_area :ingredient %>
  </div>

<div class="field">
    <%= form.label :steps %>
    <%= form.rich_text_area :step %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/food_recipes/edit.html.erb
<h1>Editing Food Recipe</h1>

<%= render 'form', food_recipe: @food_recipe %>

<%= link_to 'Show', @food_recipe %> |
<%= link_to 'Back', food_recipes_path %>

app/views/food_recipes/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>
<div class="row">
  <% @food_recipes.each do |food_recipe| %>
<div class="col-md-4">
  <div class="food_recipe-box"> 
  <% if food_recipe.image? %> 
    <%= link_to (image_tag food_recipe.image.url, class: "food_recipe-index"), food_recipe %>
  <% end %>
    <ul>
        <i class="fas fa-pizza-slice"></i>
        <li><%= food_recipe.title %></li>
        <li><%= food_recipe.description %></li>
        <li><%= link_to 'Show', food_recipe %>
        <%= link_to 'Edit', edit_food_recipe_path(food_recipe) %>
      <%= link_to 'Destroy', food_recipe, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    </ul>
    </div> 
  </div>
    <% end %>
</div>
<br>

<%= link_to 'New Food Recipe', new_food_recipe_path %>
</div>

app/views/food_recipes/new.html.erb
<h1>New Food Recipe</h1>

<%= render 'form', food_recipe: @food_recipe %>

<%= link_to 'Back', food_recipes_path %>

app/views/food_recipes/search.erb
<h1>Search Results</h1>

<div class="container">
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>
<div class="row">
  <% @food_recipes.each do |food_recipe| %>
<div class="col-md-4">
  <div class="food_recipe-box"> 
  <% if food_recipe.image? %> 
    <%= link_to (image_tag food_recipe.image.url, class: "food_recipe-index"), food_recipe %>
  <% end %>
    <ul>
        <li><%= food_recipe.title %></li>
        <li><%= food_recipe.description %></li>
        <li><%= link_to 'Show', food_recipe %>
        <%= link_to 'Edit', edit_food_recipe_path(food_recipe) %>
      <%= link_to 'Destroy', food_recipe, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    </ul>
    </div> 
  </div>
    <% end %>
</div>
<br>

<%= link_to 'New Food Recipe', new_food_recipe_path %>
</div>

app/views/food_recipes/show.html.erb
<center>
<div class="container">
	<div class="show-box">
	<br> </br>
	<% if @food_recipe.image? %>
		<%= image_tag @food_recipe.image.url, class: "food_recipe-show" %>
	<% end %>
<p>
  <strong>Title:</strong>
  <%= @food_recipe.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food_recipe.description %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @food_recipe.ingredient %>
</p>

<p>
  <strong>Steps:</strong>
  <%= @food_recipe.step %>
</p>

<%= link_to 'Edit', edit_food_recipe_path(@food_recipe) %> |
<%= link_to 'Back', food_recipes_path %>
	</div>
</div>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-light bg-dark">
        <a class="navbar-brand" href="/">Recipe App</a>
          <ul class="nav navbar-nav">
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? -%>
              <li><%= link_to 'Account', edit_user_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
              </ul>
        <% else -%>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>      
              </ul>
        <form class="form-inline my-2 my-lg-0" action="/search">
          <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav>
  
  </header>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/receita/_form.html.erb
<%= form_with(model: receitum, local: true) do |form| %>
  <% if receitum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receitum.errors.count, "error") %> prohibited this receitum from being saved:</h2>

      <ul>
        <% receitum.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/receita/edit.html.erb
<h1>Editing Receitum</h1>

<%= render 'form', receitum: @receitum %>

<%= link_to 'Show', @receitum %> |
<%= link_to 'Back', receita_path %>

app/views/receita/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Receita</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receita.each do |receitum| %>
      <tr>
        <td><%= receitum.title %></td>
        <td><%= receitum.description %></td>
        <td><%= link_to 'Show', receitum %></td>
        <td><%= link_to 'Edit', edit_receitum_path(receitum) %></td>
        <td><%= link_to 'Destroy', receitum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receitum', new_receitum_path %>

app/views/receita/new.html.erb
<h1>New Receitum</h1>

<%= render 'form', receitum: @receitum %>

<%= link_to 'Back', receita_path %>

app/views/receita/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @receitum.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @receitum.description %>
</p>

<%= link_to 'Edit', edit_receitum_path(@receitum) %> |
<%= link_to 'Back', receita_path %>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>String</th>
      <th>Description</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.string %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.text %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>String:</strong>
  <%= @recipe.string %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Text:</strong>
  <%= @recipe.text %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>